import Headers from "../../components/Headers";
import React from "react";
import Footer from "../Footer/Footer";
function TermsConditionPage() {
  return (
    <div>
      <Headers />
      <div className='h-full p-3 font-main max-w-7xl mx-auto ' >
        <p className=' font-bold text-2xl mb-2'>Terms and Conditions </p>
        <i>These Terms of Use were last updated on August 20, 2024.</i>
        <pre className='text-justify leading-relaxed whitespace-pre-wrap'
          style={{
            fontFamily: 'IBM Plex Sans, sans-serif',
          }}>
          {`
CONSUMER FRAUD ALERT: PROTECT YOURSELF, BE CAREFUL WHEN A STRANGER ASKS YOU TO SEND MONEY, ESPECIALLY FOR INTERNET AUCTIONS, NEWSPAPER OR TELEPHONE OFFERS.  Quick T is not an escrow service provider. Customer and Receiver agree not to use Services for escrow purposes.
These Terms of Use were last updated on August 18th, 2024.
1. INTRODUCTION
THESE TERMS OF USE ("TERMS") BIND YOU, THE COMPANY YOU REPRESENT, AND THE COMPANY THAT REGISTERED YOU (COLLECTIVELY "YOU") TO THE TERMS AND CONDITIONS SET FORTH HEREIN IN CONNECTION WITH YOUR USE OF QUICK T ("OUR", "WE", "US", OR QUICK T) , a company registered under ASIC ( Australian Securities and Investments Commissions, A.C.N 649535688 PTY Ltd ) and registered as an AUSTRAC independent remittance dealer number IND100789859-001, money transfer services SOFTWARE, WEBSITES, MOBILE APPLICATIONS OR CONNECTED APPLICATIONS, OR OTHER OFFERINGS ON OUR WEBSITE (COLLECTIVELY, OUR "SERVICES"). BY USING ANY OF QUICK T SERVICES OR CLICKING ON THE “Send” and/or "Confirm & Send" BUTTON, YOU AGREE TO BECOME BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO ALL THESE TERMS, DO NOT USE THE QUICK T SERVICES. QUICK T ACCEPTANCE IS EXPRESSLY CONDITIONED UPON YOUR ASSENT TO ALL THESE TERMS, TO THE EXCLUSION OF ALL OTHER TERMS. IF THESE TERMS ARE CONSIDERED AN OFFER BY QUICK T, ACCEPTANCE IS EXPRESSLY LIMITED TO THESE TERMS.
Pre Dispute- clause:
IMPORTANT: BY AGREEING TO THESE TERMS YOU AGREE TO RESOLVE DISPUTES WITH  QUICK T AMICABLY (AND WITH VERY LIMITED EXCEPTIONS, NOT IN COURT)
All capitalized terms used and not otherwise defined herein shall have the meaning ascribed to them in QUICK T Privacy Policy ("Privacy Policy"), 
Any version of these Terms of Use in a language other than English is provided for convenience and you understand and agree that the English language will control if there is any conflict.
2. PRIVACY POLICY
Any personal information submitted in connection with Your use of the Services is subject to Our Privacy Policy, which is hereby incorporated by reference into these Terms.
3. GENERAL
THE SERVICES, AS DEFINED BELOW, ARE PROVIDED TO YOU SUBJECT TO THE FULL TERMS AND CONDITIONS AND APPLICABLE LAW.
 
Our Services enable general users the "Users" to send money globally to Lebanon. The Services include, without limitation, electronic money transfers and taking feedback from Users.
From time to time, We may update these Terms to clarify our practices or to reflect new or different practices, such as when We add new features, and QUICK T reserves the right in its sole discretion to modify and/or make changes to these Terms at any time. Modifications will become effective on the day they are posted unless stated otherwise.
Your continued use of Our Services after changes become effective shall mean that You accept those changes. You should visit the Terms regularly to ensure You are aware of the latest version of the Terms, as any revised Terms shall supersede all previous Terms.
QUICK T may modify the Services or discontinue their availability at any time.
You may only access the Services for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to Your use of the Services.
You are solely responsible for all service, telephony, data charges and/or other fees and costs associated with Your access to and use of the Services, as well as for obtaining and maintaining all telephone, computer hardware, and other equipment required for such access and use.
If You elect to access or use Our Services that involve payment of a fee, then You agree to pay, and will be responsible for payment of, that fee and all taxes associated with such access or use. If You provide credit card information to pay for such fees then You hereby represent and warrant that You are authorized to supply such information and hereby authorize QUICK T to charge Your credit card on a regular basis to pay the fees as they are due.
If Your payment method fails or Your Account is past due, then We may collect fees owed using other collection mechanisms. This may include charging other payment methods on file with Us and/or retaining collection agencies and legal counsel. We may also block Your access to any Services pending resolution of any amounts due by You to QUICK T.
All of Your use, access and other activities relating to the Services must be in compliance with all applicable laws and regulations, including, without limitations, laws relating to copyright and other intellectual property use, and to privacy and personal identity. Further, access to Our Services from territories where their contents are illegal is prohibited. Those who choose to access or use the Services from locations outside Australia do so at their own initiative and are responsible for compliance with all local rules including, without limitation, rules about the internet, data, e-mail, or privacy. You further agree to comply with all applicable laws regarding the transmission of technical data exported from the country in which You reside. If You use the Services or Third Party Platforms (as defined in the next section) from countries outside of Australia You must agree to abide by all local rules regarding online conduct and acceptable content.
WHEN YOU SEND MONEY FROM AUSTRLALIA OR OTHER COUNTRY TO LEBANON USING QUICK T WEBSITES OR MOBILE APPLICATIONS, THE MONEY TRANSFER SERVICES (COLLECTIVELY, THE “SERVICE(S)”) ARE PROVIDED BY QUICK T (A.C.N 649 535 688 PTY LTD). THE AUSTRLIAN AND OTHER COUNTRY PORTIONS OF THE SERVICES ARE TYPICALLY PROVIDED THROUGH QUICK T WEBSITE OR MOBILE APPLICATION. LEBANON PORTION IS PROVIDED BY QUICK T AGENTS IN LEBANON. ALL PORTIONS OF THE SERVICES (AUSTRALIAN, OTHER COUNTRIES AND LEBANON ARE SUBJECT TO THESE TERMS AND CONDITIONS (“AGREEMENT”) AND APPLICABLE LAW. 
Service and funds availability depend on certain factors including the Service selected, the selection of delayed delivery options, special terms applicable to each Service, amount sent, destination country, currency availability, regulatory or consumer protection issues, identification requirements, delivery restrictions, agent location hours, and differences in time zones. “Receiver(s)” or “Final Receiver(s)” means the recipient designated by the consumer (“You” or “Your”) to receive funds sent by You via QUICK T website and/or mobile applications. 
Receiver will normally receive funds in cash, check, or a combination thereof; with some Services, funds may be credited to a bank account, prepaid, debit or credit card (“Card(s)”), mobile wallet (“MWallet(s)”), or similar account (collectively, “Account(s)”). Receiver may be able to elect a payout method that differs from the payout method You specify; You authorize QUICK T to honor Receiver’s election of payout method. Receivers who choose to receive funds through a payout method other than cash or in a currency other than the one You selected may incur additional fees to access funds. Certain countries and/or jurisdictions may impose a tax, fee and/or tariff on Receiver’s receipt of, or access to, transferred funds. Transactions may be reported to applicable authorities. Messaging and notification services may be included for additional fees. In Lebanon, Receiver is required to provide photo identification, address phone number and PER (Personal Identification Number) associated with transfer to receive funds in cash. QUICK T RELIES ON THE INFORMATION YOU PROVIDE US TO SEND MONEY. PLEASE REVIEW ALL TRANSACTION DETAILS FOR ACCURACY BEFORE CONTINUING YOUR TRANSACTION.
4. ADMINISTRATION CHARGE: 
Transactions not picked up or canceled by You within 6 months of the send date will be assessed a non-refundable administration charge of up to USD 1 per month from the send date, not to exceed USD 50, which will be deducted from the amount sent (or where such charge exceeds the maximum amount permitted by law, the maximum amount permitted by law).
5. REFUNDS: 
Subject to applicable law: (i) transactions may be canceled for a refund of the transfer amount, unless the funds have been picked up or deposited at the time QUICK T receives Your written request; (ii) for certain services, excluding QUICK T’s bill payment and prepaid products and services, QUICK T may provide a transfer fee refund if funds are not available to Receiver; and (iii) QUICK T may charge You a fee to refund the transfer amount back to You in those instances where Receiver rejects Your funds. Qualifying refunds for transactions will be made within 60 days of receipt of Your valid written request. QUICK T may issue Your refund through a QUICK T money transfer or QUICK T may issue the refund to the credit / debit card or bank account that was used to pay for the transaction. 
Notwithstanding the foregoing, and subject to applicable law, international transactions may be canceled for a full refund of the transfer amount and fees paid within 5 minutes of payment, unless the funds have been picked up or deposited. You may also receive a full refund in certain circumstances if You successfully assert an error or as otherwise provided under applicable law.
6. SPECIFIC OBLIGATIONS OF SENDERS
As a Sender, You represent, warrant and covenant that:
1.	You have read, understood, and agree to be bound by the pricing information before using the Services.
2.	You are over the age of 18, 
3.	You will not upload, post or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes or any other form of solicitation (commercial or otherwise) through the Services.
4.	You will not post or provide any inappropriate, offensive, racist, hateful, sexist, pornographic, false, misleading, incorrect, infringing, defamatory or libelous content or information.
5.	You will not copy, modify, reverse engineer, reproduce, distribute, publicly display, publicly perform, communicate to the public, create derivative works from, deface, tarnish, mutilate, hack, interfere with, or otherwise use and exploit any Company Content, the Services You will not frame or embed the Services to circumvent the Services.
6.	You will not impersonate another person or gain unauthorized access to another person's Account.
7.	You will not introduce any virus, worm, spyware or any other computer code, file or program that may or is intended to damage or hijack the operation of any hardware, software or telecommunications equipment, or any other aspect of the Services or operation thereof; scrape, spider, use a robot or other automated means of any kind to access the Services.
7. LIMITATIONS OF LIABILITY: 
TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW: (1) IN NO EVENT SHALL QUICK T BE LIABLE FOR DAMAGES WHETHER CAUSED BY NEGLIGENCE ON THE PART OF ITS EMPLOYEES, SUPPLIERS OR AGENTS OR DUE TO INACCURACIES OR SYSTEM OUTAGES OR OTHERWISE, BEYOND THE SUM OF USD10 (in addition to refunding the transfer amount and transfer fee and (2) IN NO EVENT SHALL QUICK T OR ITS AGENTS BE LIABLE FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR THE LIKE.
Inaccuracies. A possibility exists that the Services provided on any Third Party Platform could include inaccuracies or errors, or information or materials that violate these Terms. Additionally, a possibility exists that unauthorized alterations could be made by third parties to the Services available on any Third Party Platform. Although QUICK T attempts to ensure the integrity of the Services on Third Party Platforms, we make no guarantees as to the Services' completeness or correctness. In the event that a situation arises in which the Services' completeness or correctness is in question, please submit a request to support@quickt.com.au(with the subject line "Inaccuracies in Services on Third Party Platform Name") with, if possible, a description of the Services to be checked and the location (URL) where such Services can be found on Our Services or Third Party Platform at issue, as well as information sufficient to enable Us to contact You. We will try to address Your concerns as soon as reasonably practicable. 
System Outages. QUICK T periodically schedules system downtime for the Services for maintenance and other purposes. Additionally, unplanned system outages may occur. You agree that QUICK T has no responsibility and is not liable for: (a) the unavailability of the Services including those available on Third Party Platforms; (b) any loss of materials, data, transactions or any other information or materials caused by such system outages; (c) the resultant delay, mis-delivery, or non-delivery of data, transactions or any other information or materials caused by such system outages; or (d) any outages caused by any third parties, including without limitation, any companies or servers hosting the Services, any Internet service providers, any Third Party Platforms, or any Internet facilities and networks.
8. WARRANTY DISCLAIMER
THE SERVICES, AND ANY OTHER MATERIALS MADE AVAILABLE ON OR THROUGH THE USE OF THE SERVICES ARE PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, QUICK T AND ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS AND AGENTS, DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, IMPLIED WARRANTIES OF TITLE, NON- INFRINGEMENT, ACCURACY, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND ANY WARRANTIES THAT MAY ARISE FROM COURSE OF DEALING, COURSE OF PERFORMANCE OR USAGE OF TRADE. QUICK T AND ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS AND AGENTS DO NOT WARRANT THAT YOUR USE OF THE SERVICES WILL BE UNINTERRUPTED, ERROR-FREE OR SECURE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE SERVICES, THE SUBMISSIONS, THE SERVER(S) ON WHICH THE SERVICES ARE HOSTED, OR ANY SERVICES AVAILABLE ON ANY THIRD PARTY PLATFORM ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. NO OPINION, ADVICE OR STATEMENT OF QUICK T OR ITS AFFILIATES, LICENSORS, SUPPLIERS, ADVERTISERS, SPONSORS, AGENTS, MEMBERS OR VISITORS, WHETHER MADE THROUGH THE USE OF THE SERVICES, OR ON THIRD PARTY PLATFORMS OR OTHERWISE, SHALL CREATE ANY WARRANTY. YOUR USE OF THE SERVICES, INCLUDING WITHOUT LIMITATION ANY SERVICES PROVIDED ON ANY THIRD PARTY PLATFORM, ARE ENTIRELY AT YOUR OWN RISK.
9. INDEMNIFICATION
You hereby indemnify, defend and hold harmless QUICK T, and its affiliates, officers, directors, agents, partners, employees, licensors, representatives and third party providers from and against all reasonably foreseeable losses, expenses, damages, costs, claims and demands, including reasonable attorneys' fees and related costs and expenses, due to or arising out of Your breach of any representation or warranty hereunder
Statute of Limitations. Any claim or cause of action arising out of or related to use of the Services, the Terms, or any services or information available through Third Party Platforms, must be filed within 3 days after such claim or cause or action arose regardless of any statutes or law to the contrary. In the event any such claim or cause of action is not filed within such 3 days period, such claim or cause of action are forever barred.
10. INTERNATIONAL TRANSACTIONS, CURRENCY EXCHANGE 
When You send money outside Australia, You are contracting with both QUICK T and its AGENT, which are conducting two separate money transfer transactions in order to make the money available to Final Receiver. In the first transaction, You are engaging QUICK T to collect Your money.  In the second transaction, You are engaging QUICK T to convert Your money into the correct currency and make the funds available to Final Receiver outside Australia In addition to the transfer fees, which are charged by QUICK T OR its AGENT, a currency exchange rate will be applied. The received currency is converted to US currency at an exchange rate set by QUICK T unless the laws of Australia do not permit QUICK T to set an exchange rate. Any difference between the rate given to You and the rate received by QUICK T will be kept by QUICK T (and, in some cases, its AGENTS) in addition to the transfer fees. Subject to applicable law, the actual or estimated currency exchange rate applicable to Your transaction will be provided on the written disclosures provided to You by QUICK T. Payouts will generally be made in US currency. 
11. SPECIAL TERMS FOR TRANSACTIONS FROM ACCOUNTS 
Where available, QUICK T may allow You to pay for the Services by using an Account. The bank or other provider of an Account, including card issuers (the “Account Provider”) may impose additional fees on Your Account. The agreement with the Account Provider governs use of an Account and provides the rights and liabilities of the holder of the Account. Unless required by applicable law, QUICK T accepts no responsibility to You or any Account holder for any fees imposed by an Account Provider. If the currency You select for Your transactions is not the currency in which an Account is denominated, the Account Provider may convert the funds at its own currency exchange rate or reject the transfers.  Your use of an Account must be limited to personal or individual use only and not for use by or on behalf of any business or legal entity. QUICK T may use an Automated Clearing House (“ACH”) network, book transfer, electronic funds transfer, wire transfer or other methods to process transactions relating to an Account. QUICK T is not responsible for actions taken by the Account Provider, such as improperly posting the transactions.  The total due is payable before QUICK T processes the transactions. If QUICK T does not receive authorization from the Account Provider, the transactions will not be processed, and funds will not be transmitted to the Final Receiver. Each time You use your Account to pay for Services, You agree that QUICK T is authorized to charge Your Account for the total disclosed to You relating to the transactions.
IMPORTANT NOTICE FOR USING YOUR ACCOUNT TO PAY FOR THE TRANSACTIONS: By initiating the transactions from an Account, You (i) affirm You are the owner of the Account and have authority to initiate the transaction and (ii) authorize QUICK T to initiate electronic debits and credits to Your Account to process and correct errors and resubmit the debit or credit, according to applicable rules, if a transaction cannot be completed. QUICK T may by law be liable for damages caused by its failure to debit Your Account in accordance with these terms and conditions, in the correct amount or in a timely manner when properly instructed by You. However, QUICK T will not be liable where: (1) You do not have enough money available in Your Account; (2) Your Account is closed or withdrawals restricted; (3) the transaction exceeds dollar or frequency limitations imposed by QUICK T or Your Account Provider; (4) circumstances beyond QUICK T’s control (such as flood, fire, power outages, mechanical or system failures); (5) Your Account Provider does not honor the transactions, the transactions are not processed or the transactions are returned by Your Account Provider; (6) Your instructions are lost or delayed in transmission to QUICK T; (7) QUICK T fails to process your transactions because of a reasonable security concern or the Service option has been discontinued or suspended, or QUICK T otherwise advises You that Your request will not be processed; and (8) other exceptions allowed by applicable law.
12. IDENTITY AND LOCATION VERIFICATION: 
YOU AUTHORIZE QUICK T TO REQUEST YOUR MOBILE CARRIER TO USE YOUR MOBILE SUBSCRIBER DETAILS FOR VERIFYING YOUR IDENTITY. THOSE DETAILS MAY INCLUDE NAME, BILLING ADDRESS, EMAIL, AND PHONE NUMBER. THIS INFORMATION MAY ALSO INCLUDE LOCATION INFORMATION, IF AVAILABLE.
13. USE OF THE QUICK T WEBSITE, MOBILE DEVICE AND TABLET SERVICES:
A. LOCATION BASED SERVICES: You acknowledge and authorize that information concerning the location of your mobile device, tablet or computer may be used to assess location. Location may be obtained at any time while logged into the website, mobile and tablet devise sites and applications (the “Website”). You expressly agree that You authorize QUICK T to collect and use Your location as a part of the QUICK T and eligibility for use of the Website.

B. INTELLECTUAL PROPERTY: The QUICK T Website, mobile application, the Services, the content, and all intellectual property therein (including but not limited to authors, patents, database rights, trademarks and service marks) are owned by QUICK T, its affiliates or third parties, and all right, title and interest therein and thereto shall remain the property of QUICK T, its affiliates and/or such third parties. The Website, mobile applications and Services may be used only for the purpose permitted by these Terms and Conditions. You may view and retain a copy of the pages of the Website only for Your own personal, non-commercial use. You may not duplicate, publish, modify, create derivative works from, participate in the transfer of, post on the World Wide Web, or in any way distribute or exploit the Website, the mobile applications,  the Service or any portion thereof for any public or commercial use without the express written consent of QUICK T. You shall not (i) use any robot, spider, scraper or other automated device to access the Website, mobile application or Service; or (ii) remove or alter any author, trademark or other proprietary notice or legend displayed on the Website (or printed pages thereof) or mobile application. The name QUICK T and other names and indicia of ownership of the Services are the exclusive marks of QUICK T or other third parties. Other product, service and company names appearing on the Website may be trademarks of their owners.

C. LINKS TO OTHER SITES: The Website may contain links and pointers to other World Wide Web Internet sites and resources (the “Linked Sites”). Links to any Linked Site do not constitute an endorsement by or association with QUICK T or any of its affiliates. Links do not imply that QUICK T is associated with or legally authorized to use any trademark, trade name, logo or author symbol displayed in or accessible through the links, or that any Linked Sites are authorized to use any trademark, trade name, logo or author symbol of QUICK T or any of its affiliates. You should direct any concerns regarding any Linked Site to such Linked Site’s site administrator or webmaster. QUICK T does not represent or endorse the accuracy or reliability of, and expressly disclaims, any advice, opinion, statement, or other information displayed or distributed through any Linked Site. You agree that reliance upon any opinion, advice, or information displayed on or otherwise available through any Linked Site shall be at Your sole risk.
14. PRIVACY
We may collect and disclose personal information to third parties as explained in our Privacy Statement. To get a copy, visit QUICK T Privacy Policy. We collect personal information, for example, when You transact with us (e.g., using the Services) and other companies; submit information on applications, forms, and by other means; use or visit our or other apps or online sites; enter a promotion; register for communications; or join a loyalty program.  We also collect information from many sources and may collect, track and combine information across devices, platforms and channels.  Information disclosed may include financial data (e.g., information on transactions with us and other financial matters), contact information, identification, computer, mobile device and social network information.  Recipients may include financial and non-financial companies, service providers, government agencies and direct marketers. You may direct us to limit certain disclosures, and Your choice will apply until You change Your choice or we delete Your data. To limit disclosures (opt out), email support@quickt.com.au

15. CONSUMER FRAUD ALERT
PROTECT YOURSELF. BE CAREFUL WHEN A STRANGER ASKS YOU TO SEND MONEY, ESPECIALLY FOR INTERNET AUCTIONS, NEWSPAPER OR TELEPHONE OFFERS. QUICK T does not guarantee delivery or suitability of goods or services paid for with Services. QUICK T is not an escrow service provider. You and Receiver agree not to use Services for escrow purposes.
16. TERMS OF SERVICE
When you confirm & send your transaction, you will get an online receipt from Quick T that you can print or download to your device and you can share the amount transferred and the transfer id with your receiver. It is the responsibility of the receiver to track the transfer and receive the money from Quick T nominated agent.
17. RESOLUTION OF DISPUTES: 
Any dispute arising from or relating to this transaction shall be resolved amicably. If you agree to resolving disputes amicably then YOU WILL WAIVE ANY RIGHT TO A TRIAL BY JURY OR JUDGE IN COURT AND ANY RIGHT TO PARTICIPATE IN A CLASS ACTION. If you do not agree, do not use QUICK T SERVICES, WEBISTES OR MOBILE APPLICATIONS.
18. MISCELLANEOUS
Entire Agreement. This Agreement, together with all items incorporated by reference, embodies the entire understanding among the parties. It supersedes all prior understandings and cannot be modified orally. QUICK T has the right to assign this Agreement to any party, at any time without Your consent. 
Governing law. These Terms and Your use of the Services shall be governed by the substantive Australian laws without reference to its choice or conflicts of law principles that would require the application of the laws of another jurisdiction, and shall be considered to have been made and accepted in Lebanon. 
Language. The English language version controls if there is an inconsistency between English and non-English Agreement versions. You and Receiver represent that Your use of Services does not violate: (a) any law, including, without limit, laws relating to money laundering, illegal gambling activities, support for terrorist activities or fraud; and/or (b) this Agreement. Information provided to QUICK T shall be truthful and complete. You shall indemnify QUICK T and its Agents for all losses of any kind (including attorney fees) arising out of any Agreement breach by You or Receiver. QUICK T reserves the right to change Services without notice. QUICK T and its Agents may refuse to provide Services to any person.
Severability. If any provision of these Terms is found to be illegal, void or unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions of these Terms.
Waiver. A provision of these Terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of QUICK T to exercise or enforce any right or provision of these Terms will not constitute a waiver of such right or provision.
Notice. Any notice or other communication to be given hereunder will be in writing and given by facsimile, postpaid registered or certified mail return receipt requested, or electronic mail.
No Agency. Nothing in these Terms shall be construed as making either party the partner, joint venture, agent, legal representative, employer, contractor or employee of the other. Neither QUICK T nor any other party to these Terms shall have, or hold itself out to any third party as having, any authority to make any statements, representations or commitments of any kind, or to take any action that shall be binding on the other except as provided for herein or authorized in writing by the party to be bound.


`}
        </pre>
      </div>
      <Footer />

    </div>
  )
}

export default TermsConditionPage;
