import React from 'react'
import Footer from '../Footer/Footer'
import Headers from "../../components/Headers";

const PrivacyPolicyPage = () => {
    return (
        <div>
            <Headers />
            <div className='h-full p-3 font-main max-w-7xl mx-auto ' >
                <p className=' font-bold text-2xl mb-2'>Privacy Policy  </p>
                <i>This Privacy Policy was last updated on August 18th,2024.</i>
                <pre className='text-justify leading-relaxed whitespace-pre-wrap'
                    style={{
                        fontFamily: 'IBM Plex Sans, sans-serif',
                    }}>
                    {`
All capitalized terms used and not otherwise defined herein shall have the meaning ascribed to them in Quick T’s Terms of Use.
Any version of this Privacy Policy in a language other than English is provided for convenience and You understand and agree that the English language will control if there is any conflict with any non-English versions.
Quick T a company registered under ASIC ( Australian Securities and Investments Commissions, A.C.N 649535688 PTY Ltd ) and registered as an AUSTRAC independent remittance dealer IND100789859-001 ), Services include, without limitation, electronic money transfers and taking feedback from Users, SOFTWARE, WEBSITES, MOBILE APPLICATIONS OR CONNECTED APPLICATIONS, OR OTHER OFFERINGS ON OUR WEBSITE (COLLECTIVELY, OUR "SERVICES"), referred to hereinafter as (Quick T, “We", "Us", or "Our") respects Your rights regarding Your privacy and information, and We provide this Privacy Policy ("Privacy Policy") to help You understand how We collect, use, share, store and disclose information We obtain from or about You when You use the Services. This Privacy Policy applies to when You use Our Services where We provide a link to this Privacy Policy, unless otherwise stated or unless We provide a link to a different policy. This Privacy Policy also describes the choices available to You regarding the use of, Your access to and how to update and correct Your information.
As used herein the term "use" shall mean use, access, install, sign into, connect with, download, visit or browse the Services, as defined in the Terms of Use.
THIS IS A LEGALLY BINDING AGREEMENT BETWEEN YOU AND QUICKT, AND BY USING THE SERVICES, YOU AGREE TO THE TERMS OF THIS PRIVACY POLICY AND THE Terms of Use. You should review this Privacy Policy in conjunction with Our Terms of Use and any other agreement or policy provided by Us that governs Your use of the Services.
You should not use the Services if You do not agree with this Privacy Policy, Our Terms of Use and any other agreement or policy that governs Your use of the Services.
1. Information You Provide to Us Directly
Quick T may collect different information from or about You depending on the manner in which You use the Services. The following examples are provided to help You better understand the information We may collect through Your use of the Services.
Please note Quick T is not responsible for how others use information that is publicly available or otherwise accessible to others who have access to the Services.
When You use the services or sign up for and use the Services (including through a Third Party Platform) We will collect any information You provide to Us directly such as the following:
Sender Information:
In order to use certain features of the Services, such as sending money electronically, You are required to enter data on you, and in that case, We will collect and store any information You provided to Us, such as e-mail address, password, address, Your date of birth, and age, telephone number, copy of official identification document and we will assign You a unique identifying number (“Sender /Registration Information”).
Receiver Information:
In order to use certain features of the Services, such as sending money electronically, You are required to enter data on the receiver and in that case, We will collect and store any information You provided to Us, such as receiver e-mail address, telephone number, copy of official identification document and we will assign a unique identifying number to the receiver (“Receiver Information”).
Profile Information:
You may also have the option of providing additional information about Yourself, including but not limited to a photo, headline, website link, social media profiles, or other information you may choose to enter ("Profile Information") to create a profile ("Profile"). Your Profile and Profile Information will be publicly viewable to others.
Public Posting / Shared Content:
Some of the Services may allow You to interact with other Users and/or post, share, communicate or otherwise transmit content publicly, (collectively "Shared Content" or "Public Posting"). We may collect and store Public Postings and Shared Content. Shared Content or Public Postings may be publicly available or viewable by others depending on where such content is posted.
You hereby grant Quick T  a non-exclusive right and license to reproduce, distribute, publicly perform, offer, market and otherwise use and exploit the Public Postings and Shared Content.
Electronic Transaction Information:
In order to use certain features of the Services, such as sending money electronically, You are required to enter data on the transaction, We will collect and store any information You provided to Us, such as and not limited to amount sent, currency exchange rates and we will assign a unique identifying number to the transaction (“Personal Individual Reference” (PER)).
You hereby consent to Our sharing of Registration/Sender Information (except for your email address), Profile Information, sender information, transaction information. 
Payment Information:
If You make any payment through our Services, such as for sending money, We may collect certain information regarding Your payment (such as Your name and address) as necessary to process Your order. You will be required to provide certain payment and billing information directly to our payment processing partners, including but not limited to Your name, credit/debit card information, billing address. We do not access, store or collect Your credit/debit card information.
If You are a Sender, We may enable You to link Your PayPal account or other payment account to the Services so that You can pay Us. When You link such account, You allow Us to collect and use certain information from such accounts to process those payments, such as Your payment account email address or account ID, physical address, and other information necessary for Us to deduct payment of such account. We do not access, store, or collect Your payment card or bank account information. The collection, use, and disclosure of Your information will also be subject to the privacy policies and other terms of the payment account providers. You should review such privacy policies, terms, and other agreements.
Information Received Through Your Third Party Platform:
The Services may contain third party links or allow You to access the Services through Third Party Platforms, such as Facebook. If You use Our Services on or through a Third Party Platform, including via any mobile and/or other Internet connected devices (“Wireless Devices”), or click on third party links, the collection, use, and disclosure of Your information and Your use of the Services will also be subject to the privacy policies and other terms of such third parties or Third Party Platforms. You should review such privacy policies, terms, and other agreements.
When You use Our Services through a Third Party Platform, You allow Us to collect and use certain information from Your Third Party Platform profile or account as permitted by the terms of that Third Party Platform and Your privacy settings and in accordance with this Privacy Policy.
By way of example only, We may collect some or all of the following information from Your Third Party Platform account when You register or use the Services on or through a Third Party Platform:
•	Your full name
•	Your profile picture or its URL
•	Your ID Number, which is linked to publicly available information such as Your name and profile photo
•	The login e-mail address
•	Your physical location and that of Your access devices, including any Wireless Device
•	Your gender
•	Your birthday
•	List of friends or contacts
You may choose not to allow the Third Party Platform to provide Us with certain information about You, but You might not be able to use certain features of Our Services if You enable such restrictions.
Sweepstakes, promotions, and Surveys:
From time to time, We may ask You to complete a survey and/or offer You the opportunity to participate in promotions and/or sweepstakes (collectively, “Promotions”) via the Services or through a Third Party Platform. If You choose to participate in a Promotion, We will collect and store the information You provide in connection with Your participation in the Promotion, including, but not limited to, Your name, e-mail address, date of birth, and/or phone number. Such information shall be subject to this Privacy Policy unless otherwise stated in the official rules or guidelines of the Promotion or in another privacy policy governing the Promotion. Information we collect in connection with a Promotion will be used to administer the Promotion, such as by notifying winners and distributing prizes. As permitted by applicable law, Your information may also be used by Quick T or the Promotion sponsor for marketing purposes.
Your entry into the Promotion may result in the addition of Your information to our mailing list as well as to the mailing list of our promotional partners. Acceptance of a prize may require You (unless prohibited by law) to allow Us to post publicly some of Your information via our Services, such as on a winner's page. In some instances, a third-party advertiser or sponsor may operate or host a Promotion on or through our Services, and collect Your information. In those cases, where We are not the sponsor or operator of the Promotion, We have no control over the information collected and, before participating, You should review the official rules as well as the advertiser's or the sponsor's privacy policy applicable to the Promotion. All of Our Promotions are intended for people who are the age of majority in their respective state, province or country unless otherwise expressly stated.
Communications, Support Requests, Potential Abuse:
If You contact Us for assistance, or to report a problem, concern, potential abuse or other issues regarding the Services, including before You have created an Account, We may collect and store Your contact information, communication, and/or other information about You, including but not limited to Your name, e-mail address, location, operating system, IP address, any other information You provide Us in the course of such communications, and/or other information that may be collected by automated means described herein. We reserve the right to conduct further research and obtain further information as necessary. We will use the information to respond to You and research Your request/communication, all in accordance with the provisions of this Privacy Policy.
2. Information We Collect Through Automated Means
Technical and Usage Data
When You access the Services, including browsing Our services, We collect certain information by automated means. This information may include without limitation: (a) technical information about Your computer or Wireless Device, such as Your IP address, device type, operating system type and version, unique device ID, browser, browser language, domain and other systems information, platform types (collectively, “Technical Information”); and (b) usage statistics about Your interaction with the Services, including services accessed, time spent on pages or the Services, pages visited, search queries, click data, portions of the Services used, date and time, and other information regarding Your use of the Services (collectively, “Usage Data”).
This Technical Information and Usage Data, which may be linked to Your information, is collected through the use of server log files and tracking technologies, including: (i) cookies, which are small files that websites send to Your computer or Wireless Device to uniquely identify Your browser or mobile device or to store information in Your browser setting; and (ii) web beacons, which are small objects that allow Us to measure the actions of visitors using the Services. For more detailed information regarding how We use cookies and other Quick T, please review the additional information in this Privacy Policy under the Section entitled "Our Cookies Policy" 
Geolocation Information: IP addresses received from Your browser or device may be used to determine Your approximate location, such as the city, state and/or country associated with an IP address as well as currency associated with country.
3. Cookies and Data Collection Tools
Like many websites and app providers, Quick T (and/or service providers acting on Our behalf, such as Google Analytics and/or our third party advertisers) may use server log files and automated data collection tools, such as cookies, tags, scripts, device or browser fingerprints, and web beacons (collectively, "Data Collection Tools") when You access and use our Services. In some cases, We tie the information gathered by these means to Our other information You provide and that we collect as described in this Privacy Policy. These Data Collection Tools automatically track and collect certain Technical Information and Usage Data that Your browser sends when You use our Services. In some cases, We will associate this Technical Information and Usage Data with other information about You.
We use cookies for a variety of reasons, including to: (i) analyze the usage of our Services; (ii) provide a more personalized experience; (iii) allow You to more easily login to use our Services; and (iv) help make Your use of Our Services more efficient and more valuable by providing You with a customized experience and recognizing You when You return.
We may also employ web beacons or other technology for a variety of reasons such as: (i) allowing Us to know if a certain page was visited or whether an e-mail was opened; (ii) allowing Us to advertise more efficiently by excluding our current Users from certain promotional messages or identifying the source of a new installation.
You can set Your web browser to warn You about attempts to place cookies on Your computer, limit the types of cookies You allow or refuse cookies altogether; however, You may not be able to use some or all of the features of the Services, or Your experience will be different or less functional if You refuse/disable cookies.
By using Our Services, You consent to Our use of cookies, web beacons, LSOs and other Data Collection Tools, Data Analytics Tools, as described in this Privacy Policy. 
4. Analytics.
We may use third-party browser and mobile analytics services on our Service, including but not limited to Google Analytics, Full Contact, Hotjar, and Intercom. These service providers use the sort of technology described above to help us analyze how users use the Services, including by noting the third-party website from which you arrive, how often You use the Services, the events that occur within the Service, usage data, performance data, and where the application was downloaded from.
The information collected will be disclosed to or collected directly by these service providers, and We use this information to improve the Services, to better understand the functionality of the Services on a computer or other device, and to provide information that may be of interest to You.
5. Online Advertising
We may use third-party advertising technologies that allow for the delivery of advertising about our Services on other websites You visit and other applications You use. The ads may be based on various factors such as the content of the page You are visiting, information You enter such as Your age and gender, Your searches, demographic data, user-generated content, and other information we collect from You. These ads may be based on Your current activity or Your activity over time and across other websites and online services and may be tailored to Your interests.
We use third parties (e.g., ad networks and ad servers such as Google Analytics, DoubleClick and others) to help deliver these tailored advertising on other websites and in mobile applications. These third parties may place cookies or other tracking technologies on Your computer, mobile phone, or other device to collect information about Your use of the Services as discussed above and may access these cookies or other tracking technologies on Your computer, mobile phone, or other device You use to access the Services in order to serve these tailored advertisement. We also may share with third-party advertisers a hashed version of Your email address that is anonymized and cannot be used to identify you, solely in non-human readable form and content that You share publicly when using the services (e.g, user-generated content) for purposes of delivering tailored advertising.
We neither have access to, nor does this Policy govern, the use of cookies or other tracking technologies that may be placed on Your computer, mobile phone, or other device You use to access the Services by non-affiliated, third-party ad technology, ad servers, ad networks or any other non-affiliated third parties. Those parties that use these technologies may offer You a way to opt out of ad targeting as described below. You may receive tailored advertising on Your computer through a web browser. 
When using a mobile application you may also receive tailored in-application advertisements. Each operating system, iOS for Apple phones, Android for Android devices and Windows for Microsoft devices provides its own instructions on how to prevent the delivery of tailored in-application advertisements. You may review the support materials and/or the privacy settings for the respective operating systems in order to opt-out of tailored in-application advertisements. For any other devices and/or operating systems, please visit the privacy settings for the applicable device or contact the applicable platform operator.
Please note that to the extent advertising technology is integrated into the Services, You may still receive advertisements on other websites and mobile applications even if You opt-out. In that case, the advertising will not be tailored to Your interests. Also, we do not control any of the above opt-out links or whether any particular company chooses to participate in these opt-out programs. We are not responsible for any choices You make using these mechanisms or the continued availability or accuracy of these mechanisms.
6. Our Policy Concerning Children
We recognize the privacy interests of children and We encourage parents and guardians to take an active role in their children's online activities and interests. Children under the age of 13, or 16 if such children resides in the European Economic Area, should not use or attempt to use Our Services. If We learn that We have collected personal information (as defined by applicable law) from a child under 13 or a child under 16 in the Europea Economic Area, We will take reasonable steps delete such information.
Parents who believe that Quick T might have collected personal information from a child under the age of 13 may submit a request to support@quickt.com.au and request that the information be removed.
7. How We Use the Information We Collect
Quick T may use the information We collect through Your use of the Services to:
•	Perform Know Your Customer (KYC) Validation directly or through third party
•	Provide, administer, and facilitate Your use of the Services, including to display customized content;
•	Process or fulfill Your request(s) and/or order(s) for money transfer services, information or features;
•	Communicate with You concerning Your transaction by:
•	Responding to Your questions or concerns;
•	Sending You Service and administrative messages and information, including those about changes to the Service, and updates to our Terms of Use, and Privacy Policy;
•	Emailing You information or providing in app messages about Your progress in you transfer, rewards programs, new services, new features, promotions, newsletters, and other available services, which You can opt out of at any time;
•	Sending push notifications to Your Wireless device to provide updates and other relevant messages. You can manage push notifications from the "options" or "settings" page for the mobile application.
•	Understand and improve the Services and develop new products, services or features;
•	Enable User-to- User communication and interaction;
•	Manage Your Account preferences, establish Your Profile and Registration Information;
•	Facilitate the technical functioning of the Services, including without limitation to troubleshoot and resolve issues, secure the Services; and prevent fraud and abuse
•	Respond to customer support questions and issues and resolve disputes;
•	Create, review, analyze and share Technical Information;
•	Analyze trends and User traffic, track purchases and usage information;
•	Advertise our Services on third party websites or mobile applications
•	Market, process or fulfill Promotions administered or sponsored by Quick T
•	Solicit feedback from Users;
•	As required or permitted by law;
•	As We, in Our sole discretion, otherwise determine to be necessary or required to ensure the safety and/or integrity of Our Users, employees, third parties, members of the public, and/or our Services;
•	Identify unique users across devices; or
•	Tailor advertisements across devices.
8. When and How We May Share/Disclose Your Information with Third Parties
We will share Your information which may include Registration/sender Information, Receiver information, Profile Information, and Shared Content with the following third parties or under the following circumstances or as otherwise described in this Privacy Policy:
Third Party Business Partners, Service Providers, Contractors or Agents
We may share Your information with third party companies that perform services on Our behalf, or that we perform services on their behalf, including for KYC, payment processing, order fulfillment, data analysis, marketing services, advertising services (including but not limited to retargeted advertising), e-mail and hosting services, and customer services and support. 
We may also share Your information with third party companies that we partner with to provide certain services to You in connection with the Services, including but not limited to Our partners in Lebanon, telecom operators, or other similar partners. Those partners’ collection and use of information is subject to their privacy policies and other terms. You should review such privacy policies, terms, and other agreements.
About You with other Users
As mentioned above your Profile Information may be publicly viewable, including to other Users. In addition, if you ask a question to US information about you, such as your name, may be publicly viewable by other Users.
Analytics and Data Enrichment Services
As discussed above, We use third-party analytics such as Full Contact, Google Analytics, Mixpanel, and Hotjar to help understand Your usage of our services and to improve our Service. We may also use data enrichment services such as Clearbit, Intercom, and InsideView. We may provide Your contact information, Registration Information, Technical Information, Usage Data, or de-identified data or to data enrichment services to such third party analytics and data enrichment service providers, which match such information with publicly available database information, including contact and social information from other sources, such as Your email address, gender, company, job title, photos, website URLs, social network handles and physical addresses. We use this combined information to communicate with You in a more effective and customized manner.
Business Transfers, Sales, Mergers, or Divestitures
In the event that Quick T undergoes a business transition, such as a merger, acquisition, corporate divestiture or dissolution (including bankruptcy), or a sale of all or a portion of its assets, We may share, disclose or transfer all of Your information to the successor organization in such transition or during steps in contemplation of such activities (e.g., due diligence).
With Your Permission
We may share information to third parties not within scope of this Privacy Policy.
Aggregate or De-identified Information
We may disclose or use aggregate or de-identified information for any purpose.
Promotions
We may share Your information in connection with any Promotion You enter on or through the Services, as necessary to administer, market, sponsor, or fulfill the Promotion or as required by applicable laws, rules or regulations (for example, to provide winners' lists or make required filings as appropriate) or in accordance with the applicable rules of the Promotion. We may share Your information with a third party assisting us in administering the Promotion.
Advertising of Third Party Products/Services
While we do not currently offer advertising on the Services, if we do offer advertising in the future, we may use and share with third party advertisers (and other third parties) certain Technical Information, Usage Information and/or Aggregate Information to show general demographic and preference information among our Users. We may also allow advertisers to collect Technical Information or Aggregate Information, which they may share with Us, through the use of tracking technologies like cookies and web beacons. The information collected may be used to offer You targeted ad-selection and delivery in order to personalize Your User experience by increasing the likelihood that advertisements for products and services You see will appeal to You, a practice known as behavioral advertising, and to undertake web analytics (i.e. to analyze traffic and other end User activity to improve Your experience). To learn more about behavioral advertising or to opt-out of this type of advertising for participating ad networks. Please note this does not opt You out of being served ads. You will continue to receive generic ads. We do not control the above opt-out tools and are not responsible for their operation or which companies choose to participate in these programs.
Social Media Features
Our Services may include social media features, such as the Facebook Like button, links to our social media pages. Our integration of these features may allow third party social media provided to collect certain information such as Your IP address, which page You are visiting when using Our Services, and to set a cookie to enable the feature to function properly. Social media features are either hosted by a third party or hosted directly through the use of Our Services. Your interactions with these features are governed by the privacy policy of the company providing it.
Safety, Security, Cooperation with Law Enforcement, & Compliance with Legal Obligations
We may disclose Your information to third parties, if We, in our sole discretion, have a good faith belief that disclosure is: (1) permitted or required by law; (2) requested in connection with or relevant to a judicial, governmental or legal inquiry, investigation, order, or proceeding; (3) required or reasonably necessary pursuant to a valid subpoena, warrant or other legally valid inquiry or request; (4) reasonably necessary to enforce Our Terms of Use, this Privacy Policy, or any other legal agreements; (5) required to detect, prevent, or otherwise address fraud, abuse, misuse, potential violations of law (or rule/regulation), and/or security or technical issues; or (6) required or reasonably necessary in Our discretion to protect against imminent harm to the rights, property or safety of Quick T, Our Users, employees, members of the public and/or our Services. We may also disclose information about You to Our auditors or legal advisors in conjunction with accessing Our disclosure obligations and/or rights under this Policy.
9. How Do We Keep Your Information Secure?
Quick T takes appropriate security measures to protect against unauthorized access to, or unauthorized alteration, disclosure or destruction of, data that You share and We collect and store. These measures vary based on the sensitivity of the data we collect and store. Unfortunately, however, no system can be 100% secured, and We cannot guarantee that communications between You and Quick T, the Services, or any information provided to Us in connection with the information We collect through the Services will be free from unauthorized access by third parties. Unauthorized entry or use, hardware or software failure, and other factors may compromise the security of User information at any time. Your password is an important component of Our security system. As such, it is Your responsibility to protect it. Do not share Your password with any third parties. If Your password has been compromised for any reason, You should change it immediately and contact support@quickt.com.au with any concerns.
10. How to Access & Update Your Information
You may access and update Your registration information that Quick T collects and maintains in the following ways:
You may update the information You provide directly to Quick T by logging into Your Account and updating Your Account information at any time. 
To manage the information Quick T receives about You from a Third Party Platform or Wireless Device, please follow the instructions provided by the Third Party Platform or Wireless Device provider for updating Your information and changing Your privacy settings. Once Quick T receives Your information from a Third Party Platform or Wireless Device, that information is stored and used by Quick T in accordance with this Privacy Policy.
11. How to Delete Your Account and what Happens when Your Account is Terminated or Deleted
Deactivating Your Account
If You are a Sender, and wish to delete Your Sender Account, You may do so by following the steps provided in your account settings page.
Should You require any assistance or encounter any difficulty in deleting Your Account You may also contact Us via email at support@quickt.com.au , and We will make commercially reasonable efforts to respond to Your request within 24 hours.
Account Terminated or Deleted
Please be aware that even after Your Account is terminated or deleted some or all of Your information may still remain visible to others, including but not limited to any information that has been: (a) incorporated into others User's content, comments, postings, submissions; (b) copied, stored or disseminated by other Users; (c) shared or disseminated by You or others such as in a Public Posting; or (4) posted on a Third Party Platform. Termination of Your Account will not result in the removal of information collected and already put in aggregate form or information that cannot, in Our sole discretion, be removed without undue burden to Quick T. Quick Tis not able and/or obligated to remove any of Your information from a Third Party Platform.
Even after You delete Your Account or Your Account is terminated, we may retain Your information as long as we have a legitimate purpose to do so and in accordance with applicable law. In addition, Your information may not be deleted from servers of the Third Party Platform You use to access Our Services. We may retain backup copies of Your information on Our servers or databases (and/or any authorized third party servers or databases We use) for legitimate purposes such as assist with any legal obligations, resolve disputes, and enforce Our agreements. Such information may be disclosed pursuant to this Privacy Policy regardless of whether Your Account is deleted or terminated.
12. Modifications to this Privacy Policy
From time to time, We may update this Privacy Policy. If We make any material change to this Privacy Policy. Modifications will become effective on the day they are posted unless stated otherwise.
As permitted by applicable law, if You continue to use the Services, after the effective date of any change, then such access and/or use will be deemed an acceptance of and an agreement to follow and be bound by the Privacy Policy as changed. The revised Privacy Policy supersedes all previous Privacy Policies. For this reason, We encourage You to review this Privacy Policy any time You use the Services. Upon Our request, You agree to accept or sign a non-electronic version of this Privacy Policy and any other policies or agreements set forth or available through any Third Party Platform.
13. Questions
Please feel free to contact Us by submitting a request to support@quickt.com.au with any questions, concerns, or disputes You may have regarding our Privacy Policy. Please put "Privacy Policy" in the subject line so Your message can be directed to the correct person(s). 

`}
                </pre>
            </div>
            <Footer />
        </div>

    )
}

export default PrivacyPolicyPage